version: '3.8'

services:
  # Base de données (MySQL installé manuellement)
  database:
    image: qclock-db:latest
    container_name: qclock-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=rawbank_admin
      - MYSQL_DATABASE=qclock_db
    networks:
      - qclock-network

  # Application Web (Apache/PHP/Oracle)
  web-app:
    image: qclock-app:latest
    container_name: qclock-app-container
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - qclock-network

networks:
  qclock-network:
    driver: bridge