version: '3.8'

services:
  database:
    image: qclock-db:latest
    container_name: qclock-db-container
    user: root
    command: ["mysqld", "--user=mysql", "--skip-name-resolve"]
    environment:
      - MYSQL_ROOT_PASSWORD=rawbank_admin
      - MYSQL_DATABASE=qclock_db
    networks:
      - qclock-network
    restart: always

  web-app:
    image: qclock-app:latest
    container_name: qclock-app-container
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - qclock-network
    restart: always

networks:
  qclock-network:
    driver: bridge